apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: sa-east-1
      # we don't need auth block, the permission is
      # inherited from the policy created for this
      # namespace. See tofu files for more details.
