apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.4.10
      helm:
        valueFiles:
          - $values/argocd/infra/apps/argocd/values.yaml
    - repoURL: https://github.com/hooboxrobotics/infra-v2.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hooboxrobotics/infra-v2.git
      targetRevision: main
      path: manifests/infra/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
