apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: room-dash-app
  name: room-dash-app
  namespace: apps-room-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-dash-app
  template:
    metadata:
      labels:
        app: room-dash-app
    spec:
      restartPolicy: Always
      containers:
        - image: 264221247403.dkr.ecr.sa-east-1.amazonaws.com/room-dash-app:df79ef
          imagePullPolicy: IfNotPresent
          name: room-dash-app-app
          ports:
          - containerPort: 3000
            protocol: TCP
