apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer-prod-np-api-gateway-apps
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2023-12-06T03:34:55Z"
  generation: 2
  name: np-api-gateway-apps
  namespace: apps-np-api
  resourceVersion: "212228839"
  uid: 87febdd4-871e-4efd-bb2d-625fcad0327b
spec:
  rules:
  - host: gateway-api.np.hoobox.one
    http:
      paths:
      - backend:
          service:
            name: np-api-gateway-apps
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - gateway-api.np.hoobox.one
    secretName: gateway-api-np-hoobox-one-tls
status:
  loadBalancer:
    ingress:
    - hostname: a9decaed647ed4fa7bd2dd616a00e46b-1650260671.sa-east-1.elb.amazonaws.com
