logger:
  level: ALL

http:
  enabled: true
  root_path: /benthos
  debug_endpoints: true

input:
  label: input
  broker:
    inputs:
      - sql_raw:
          driver: mysql
          conn_max_open: ${MAX_OPEN_CONNECTIONS}
          dsn: ${INPUT_USERNAME}:${INPUT_PASSWORD}@tcp(${INPUT_CONNHOST}:${INPUT_CONNPORT})/shared_api_or_events?${INPUT_CONNOPTS}
          query: |
            WITH BenthosReference AS (
              SELECT
                COALESCE(MAX(d.reference_date), '2000-01-01 00:00:00') AS reference_date
              FROM benthos.datatracker d
              WHERE d.source = 'meal_orders'
            ),
            PedidosPayments AS (
              SELECT
                p.id AS id_pedido,
                p.created_at,
                rf.descricao,
                pr.gratuito,
                pr.id AS id_pedido_refeicao,
                rf.valor_centavos,
                jt.answer AS delivery_place
              FROM shared_api_payments.pedidos p
              JOIN shared_api_payments.pedidorefeicoes pr 
                ON pr.id_pedido = p.id  
              JOIN shared_api_payments.refeicaoforms rf 
                ON rf.id = pr.id_refeicao_form
              JOIN shared_api_reports.orders o
                ON o.order_id = p.id
              JOIN shared_api_reports.orderstatuses os
                ON os.order_id = o.order_id
              JOIN BenthosReference br
              LEFT JOIN JSON_TABLE(
                o.content,
                '$[*]' COLUMNS (
                  question VARCHAR(255) PATH '$.question',
                  answer   VARCHAR(255) PATH '$.answer'
                )
              ) jt
                ON jt.question = 'LOCAL DE ENTREGA'
              WHERE os.created_at >= br.reference_date
            )
            SELECT
              id_pedido,
              id_pedido_refeicao,
              created_at,
              descricao,
              delivery_place,
              CASE 
                WHEN gratuito = 0 THEN valor_centavos 
                ELSE 0
              END AS total_centavos
            FROM PedidosPayments;
    batching:
      count: 10000
      period: 20s

pipeline:
  processors:
  - label: processor_generate_meal_order_id
    bloblang: |
      root = this
      root.meal_order_id = "%s%s%s".format(this.id_pedido_refeicao, this.descricao, this.total_centavos)
      root.meal_order_id = root.meal_order_id.hash("md5").encode("hex")

  - label: processor_get_client_information
    branch:
      request_map: root = this
      result_map: |
        if this.length() > 0 {
          root.name = this.0.nome
          root.document = this.0.numero_documento
          root.delivery_date = this.0.delivery_date
        } else {
          root.name = NULL
          root.document = NULL
          root.delivery_date = NULL
        }
      processors:
      - sql_raw:
          driver: mysql
          conn_max_open: ${MAX_OPEN_CONNECTIONS}
          dsn: ${INPUT_USERNAME}:${INPUT_PASSWORD}@tcp(${INPUT_CONNHOST}:${INPUT_CONNPORT})/shared_api_payments?${INPUT_CONNOPTS}
          query: |
            SELECT
              c.nome,
              c.numero_documento,
              p.delivery_date
            FROM shared_api_payments.pedidos p
            JOIN shared_api_payments.clientes c
              ON c.hash_documento = p.documento
            WHERE p.id = ?;
          args_mapping: '[ this.id_pedido ]'
    
  - label: processor_get_payment_information
    branch:
      request_map: root = this
      result_map: |
        if this.length() > 0 {
          root.payment_method = this.0.tipo_pagamento
          root.payment_status = this.0.status
        } else {
          root.payment_method = NULL
          root.payment_status = NULL
        }
      processors:
      - sql_raw:
          driver: mysql
          conn_max_open: ${MAX_OPEN_CONNECTIONS}
          dsn: ${INPUT_USERNAME}:${INPUT_PASSWORD}@tcp(${INPUT_CONNHOST}:${INPUT_CONNPORT})/shared_api_payments?${INPUT_CONNOPTS}
          query: |
            SELECT
              p.tipo_pagamento,
              p.status
            FROM shared_api_payments.pagamentos p
            WHERE p.id_pedido = ?;
          args_mapping: '[ this.id_pedido ]'

  - label: processor_get_order_status
    branch:
      request_map: root = this
      result_map: |
        if this.length() > 0 {
          root.order_status = this.0.name
          root.modified_at = this.0.created_at
        } else {
          root.order_staus = NULL
          root.modified_at = NULL
        }
      processors:
      - sql_raw:
          driver: mysql
          conn_max_open: ${MAX_OPEN_CONNECTIONS}
          dsn: ${INPUT_USERNAME}:${INPUT_PASSWORD}@tcp(${INPUT_CONNHOST}:${INPUT_CONNPORT})/shared_api_payments?${INPUT_CONNOPTS}
          query: |
            SELECT
              s.name,
              os.created_at
            FROM shared_api_reports.orders o
            JOIN shared_api_reports.orderstatuses os
              ON os.order_status_id = o.order_status_id
            JOIN shared_api_reports.statuses s
              ON s.status_id = os.status_id
            WHERE o.order_id = ?;
          args_mapping: '[ this.id_pedido ]'

  - label: processor_check_value
    bloblang: |
      root = this
      if this.total_centavos == "0" {
        root.payment_method = "SUBSÍDIO"
      }

  - label: processor_log_prod
    switch:
      - check: 1 == 1
        processors:
          - log:
              level: WARN
              fields_mapping: |
                root.total_centavos = this.total_centavos
                root.metodo = this.payment_method

output:
  broker:
    pattern: fan_out
    outputs:
    - label: output
      sql_raw:
        driver: mysql
        conn_max_open: ${MAX_OPEN_CONNECTIONS}
        dsn: ${OUTPUT_USERNAME}:${OUTPUT_PASSWORD}@tcp(${OUTPUT_CONNHOST}:${OUTPUT_CONNPORT})/${OUTPUT_DATABASE}?${OUTPUT_CONNOPTS}
        init_statement: |
          CREATE TABLE IF NOT EXISTS mealorders (
            meal_order_id           VARCHAR(36)   NOT NULL PRIMARY KEY,
            order_id                VARCHAR(36)   NOT NULL,
            delivery_place          VARCHAR(255),
            name                    TEXT,
            document                VARCHAR(50),
            item                    TEXT,
            value                   INTEGER UNSIGNED,
            delivery_date           DATETIME,
            payment_method          VARCHAR(255),
            payment_status          VARCHAR(255),
            order_status            VARCHAR(50),
            modified_at             DATETIME
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
        query:
          REPLACE INTO mealorders VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
        args_mapping: |
          root = [
            this.meal_order_id,
            this.id_pedido,
            this.delivery_place,
            this.name,
            this.document,
            this.descricao,
            this.total_centavos,
            this.delivery_date,
            this.payment_method,
            this.payment_status,
            this.order_status,
            this.modified_at
          ]

    - label: output_set_reference_date
      processors:
        - mapping: |
            root = if batch_index() != batch_size() - 1 { deleted() }
      sql_raw:
        driver: mysql
        conn_max_open: ${MAX_OPEN_CONNECTIONS}
        dsn: ${MAIN_USERNAME}:${MAIN_PASSWORD}@tcp(${MAIN_CONNHOST}:${MAIN_CONNPORT})/benthos?${MAIN_CONNOPTS}
        init_statement: |
          CREATE TABLE IF NOT EXISTS datatracker (
            source				    VARCHAR(255)  NOT NULL  PRIMARY KEY,
            reference_date		DATETIME      NOT NULL
          );
        query: |
          INSERT INTO datatracker (source, reference_date)
          VALUES ('meal_orders', ?)
          ON DUPLICATE KEY UPDATE
            reference_date = IF(reference_date < VALUES(reference_date), VALUES(reference_date), reference_date);
        args_mapping: root = [ this.created_at ]
