apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shared-api-forms
  namespace: apps-shared-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: shared-api-forms
    creationPolicy: Owner
  dataFrom:
    # import everthing inside the SSM Paramter Path bellow
    - find:
        path: /kubernetes/hbx-prd/shared-api-forms
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
        conversionStrategy: Default
        decodingStrategy: None
      rewrite:
        # Everything tht matches with (.*) will be turned into
        # a data entry inside the secret.
        #
        # An example, the path /kubernetes/hbx-prd/shared-api-forms/DATABASE_URL
        # will become the DATABASE_URL entry.
        - regexp:
            source: "/kubernetes/hbx-prd/shared-api-forms/(.*)"
            target: "$1"
