apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-api-forms-apps
  namespace: apps-shared-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
spec:
  rules:
  - host: forms-api-hoobox.einstein.br
    http:
      paths:
      - backend:
          service:
            name: shared-api-forms
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - forms-api-hoobox.einstein.br
    secretName: forms-api-hoobox-one-tls
