apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-frontend-roompatient
  namespace: apps-app-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
spec:
  tls:
    - hosts:
        - roompatient-hoobox.einstein.br
      secretName: app-frontend-roompatient-tls
  rules:
    - host: roompatient-hoobox.einstein.br
      http:
        paths:
          - backend:
              service:
                name: app-frontend-roompatient
                port:
                  number: 80
            path: /
            pathType: Prefix
