apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shared-api-reports
  name: shared-api-reports
  namespace: apps-shared-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-api-reports
  template:
    metadata:
      labels:
        app: shared-api-reports
    spec:
      containers:
      - image: 264221247403.dkr.ecr.sa-east-1.amazonaws.com/shared-api-reports:a5b0a6
        imagePullPolicy: IfNotPresent
        name: shared-api-reports-app
        ports:
        - containerPort: 3000
          protocol: TCP
        envFrom:
          - secretRef:
              name: shared-api-reports
              optional: true
