apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: np-api-sadia-orquestrador
  name: np-api-sadia-orquestrador
  namespace: apps-np-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: np-api-sadia-orquestrador
  template:
    metadata:
      labels:
        app: np-api-sadia-orquestrador
    spec:
      containers:
        - image: 264221247403.dkr.ecr.sa-east-1.amazonaws.com/np-api-sadia-orquestrador:584082
          imagePullPolicy: IfNotPresent
          name: np-api-sadia-orquestrador-app
          ports:
          - containerPort: 3000
            protocol: TCP
          envFrom:
          - secretRef:
              name: np-api-sadia-orquestrador
              optional: true
