apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: np-api-sadia-orquestrador
  namespace: apps-shared-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: np-api-sadia-orquestrador
    creationPolicy: Owner
  dataFrom:
    # import everthing inside the SSM Paramter Path bellow
    - find:
        path: /kubernetes/hbx-prd/np-api-sadia-orquestrador
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
        conversionStrategy: Default
        decodingStrategy: None
      rewrite:
        # Everything tht matches with (.*) will be turned into
        # a data entry inside the secret.
        #
        # An example, the path /kubernetes/hbx-prd/np-api-sadia-orquestrador/DATABASE_URL
        # will become the DATABASE_URL entry.
        - regexp:
            source: "/kubernetes/hbx-prd/np-api-sadia-orquestrador/(.*)"
            target: "$1"
