apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: np-api-sadia-orquestrador
  namespace: apps-np-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
spec:
  rules:
  - host: sadia-orquestrador-hoobox.einstein.br
    http:
      paths:
      - backend:
          service:
            name: np-api-sadia-orquestrador
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - sadia-orquestrador-hoobox.einstein.br
    secretName: app-frontend-roompatient-tls
