apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-etl-benthos
  namespace: apps-data-etl
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: data-etl-benthos
    creationPolicy: Owner
  dataFrom:
    # import everthing inside the SSM Paramter Path bellow
    - find:
        path: /kubernetes/hbx-prd/data-etl-benthos
        name:
          regexp: ".*"
      rewrite:
        # Everything tht matches with (.*) will be turned into
        # a data entry inside the secret.
        #
        # An example, the path /kubernetes/hbx-prd/data-etl-benthos/DATABASE_URL
        # will become the DATABASE_URL entry.
        - regexp:
            source: "/kubernetes/hbx-prd/data-etl-benthos/(.*)"
            target: "$1"
