apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 1.0.2
      helm:
        valueFiles:
          - $values/k8s/argocd/infra/apps/argo-workflows/values.yaml
    - repoURL: https://github.com/hooboxrobotics/infra-v2.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hooboxrobotics/infra-v2.git
      targetRevision: main
      path: manifests/infra/argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
